Django_practice/urls.py
from django.contrib import admin
from django.urls import path, include, re_path as url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

base/urls.py
from django.urls import path
from base import views


urlpatterns = [
    path('', views.home, name='home'),
    path('create-account/', views.create_account, name='create-account'),
    path('log-in/', views.log_in, name='log_in'),
    path('account/<str:pk>/', views.account, name='account'),
    path('edit/<str:pk>/', views.edit, name='edit'),
    path('payment/<str:pk>/', views.payment, name='payment'),
    path('Add/<str:pk>/', views.add, name='Add'),
    path('history/<str:pk>/', views.history, name='history'),
    path('history_data/<str:pk>/<str:sk>/', views.history_data, name='history_data'),
    path('history_add/<str:pk>/<str:sk>/', views.history_add, name='add_history'),
    path('User-account/<str:pk>/', views.user_account, name='user-account'),
    path('status/', views.status, name='status')
]

base/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.


class Name(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Information(models.Model):
    name = models.CharField(max_length=200)
    host = models.ForeignKey(Name, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    dept = models.FloatField(default=0)
    balance = models.FloatField(default=0)
    interest = models.FloatField(default=0)
    bool = models.BooleanField(default=False)
    date = models.DateTimeField(default=datetime.date.today())
    birthday = models.DateTimeField(default=datetime.date(2004, 5, 11))
    interest_bool = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class NameHistory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class History(models.Model):
    name = models.CharField(max_length=200)
    host = models.ForeignKey(NameHistory, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    dept = models.FloatField(default=0)
    balance = models.FloatField(default=0)
    interest = models.FloatField(default=0)
    bool = models.BooleanField(default=False)
    current_balance = models.FloatField(default=0)
    payment = models.FloatField(default=0)
    date = models.DateTimeField()
    birthday = models.DateTimeField(default=datetime.date(2004, 5, 11))
    total = models.FloatField(default=0)

    paid_count = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Account(models.Model):
    User_Name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.User_Name

templates/account.html
{% include 'nave_bar.html' %}
{% load static %}

<!--suppress ALL -->
<html lang="">
<head><title>Account</title></head>
<link rel="stylesheet" href="{%  static 'base/css_files/account.css' %}" type="text/css">
<body>
{% block content %}
 {% for i in info.information_set.all %}
        <div class="list-container">
        <h1>Balance: {{ i.balance }}</h1>
            <div>
            <table border="1px" bgcolor="black">
                <tr>
                    <th>Name:</th>
                    <td>{{ i.name }}</td>
                </tr>
                <tr>
                    <th>Age:</th>
                    <td>{{ i.age }}</td>
                </tr>
                <tr>
                    <th>Date:</th>
                    <td>{{ i.date }}</td>
                </tr>
                <tr>
                    <th>Birthday:</th>
                    <td>{{ i.birthday }}</td>
                </tr>
                <tr>
                    <th>Interest:</th>
                    <td>{{ i.interest }}</td>
                </tr>
                <tr>
                    <th>Dept:</th>
                    <td>{{ i.dept }}</td>
                </tr>
                <tr>
                    <th>Agreement:</th>
                    {% if i.bool == False %}
                        <td>Disagree</td>
                    {% else %}
                        <td>Agree</td>
                    {% endif %}
                </tr>
            </table>

        </div>

        </div>

    <div id="list-button">
    <a href="{% url 'edit' info.id%}"><button>Edit</button></a><br>
        <a href="{% url 'payment' info.id%}"><button>Payment</button></a>
        <a href="{% url 'Add' info.id%}"><button>Add</button></a>
    <a href="{% url 'history' info.id%}"><button>History</button></a>


    </div>
 {% endfor %}
{% endblock %}

</body>
</html>

templates/add.html
{% include 'nave_bar.html' %}
{% load static %}
<!--suppress ALL -->
<link rel="stylesheet" href="{% static 'base/css_files/add.css'%}">
{% block content%}
    <form method="POST" action="">
    {% csrf_token %}
    {% for i in info.information_set.all%}
    <div class="information">
    <h1 id="cautions"> Add Payment</h1>
        <h1 id="balance">Balance: {{ i.balance }}</h1>
        <table border="2px">
            <tr>
                <th>Payment:</th>
                <td><label for="payment"></label><input id="payment" type="number" name="payment" placeholder="Amount"></td>
            </tr>
            <tr>
                <th>Name:</th>
                <td>{{ i.name }}</td>
            </tr>
            <tr>
                <th>Date:</th>
                <th>{{ date}}</th>
            </tr>
            <tr>
                <th>Dept:</th>
                <td>{{ i.dept }}</td>
            </tr>
            <tr>
                <th>Interest:</th>
                <td>{{ i.interest }}</td>
            </tr>

        </table>
    </div>
        <input type="submit" name="paid" value="saved" id="paid">
    {% endfor %}
    </form>
{% endblock %}

templates/create_account.html
{% load static %}
<html lang="">
<head>
    <title>Create-account</title>
    <link rel="stylesheet" type="text/css" href="{% static 'base/css_files/create_account.css' %}">
</head>
<body>
<div class="information">
    <form method="POST" action="">
        {% csrf_token %}
    <h1>DATE:{{ date }}</h1>
        <label for="name">Name:</label>
        <input name="name" type="text" id="name" placeholder="philip evangelista" maxlength="30" minlength="5"><br><br>
        <label for="age">Age:</label>
        <input name="age" type="Number" id="age" value="10" min="10" max="99"><br><br>
        <label for="dept">Dept:</label>
        <input name="dept" type="Number" id="dept" value="1" min="0" max="1000"><br><br>
         <label for="birthday">Birthday:</label>
        <input name="birthday" type="date" id="birthday" max="{{ date }}">

        <dl>
            <dt >Reminder</dt>
            <dd >if your dept reaches 1 month,
            then your dept will be increasing 1 peso a day</dd>
        </dl>
        <label>Agree or Disagree</label>
        <label>
            {% if value == True %}
                <input name= 'value'  type="checkbox" value="agree" checked id="value">
            {% else %}
                <input name="value" type="checkbox" value="agree" id="value">
            {% endif %}
        </label><br><br>
        <button type="submit" id='save' value="saved" name="save">Submit</button>

    </form>
</div>
</body>
    <script>
        document.getElementById('save').onclick = function(){
             let name = document.getElementById('name').value;
             if(name === '')
                alert("Sorry your name is blank yet")
             let value = document.getElementById('value').value;
             if (value !== 'agree')
                 alert('You must Agree in policy!!')
        }
    </script>
</html>

templates/edit.html
{% include 'nave_bar.html'%}
{% load static  %}
{% block content %}
    <link rel="stylesheet" href='{% static "base/css_files/edit.css" %}'>
    <form method="POST" action="">
    {% csrf_token %}
    <div class="edit-container">
        <div id="form">
             {{ form.as_p }}
        </div>

    </div>
    <input type="submit" value="Save" id="submit">
    </form>
{% endblock %}

templates/history.html
{% include 'nave_bar.html' %}
{% load static %}
{% block content %}

    <!--suppress ALL -->
     <link rel="stylesheet" href="{% static 'base/css_files/history.css' %}" type="text/css">
    <div id="list-container" method="GET">
        <h1>Payment History</h1>
    <div>
        <ul>

    {% for _, v in info.items %}

        {% for k in v.count%}
<a href="{% url 'history_data' get.id k%}">
            <li>{{k}}</li>
            </a>
        {% endfor %}
    {% endfor %}
    </ul>
    <h1>Add History</h1>
     <ul>

    {% for _, v in payment.items %}

        {% for k in v.count%}
<a href="{% url 'add_history' get.id k%}">
            <li>{{k}}</li>
            </a>
        {% endfor %}
    {% endfor %}
    </ul>
    </div>
    </div>

{% endblock %}

templates/history_data.html
{% include 'nave_bar.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'base/css_files/history_data.css' %}" type="text/css">
    <h1>{{Payment}}</h1>
    <div class="data-container">
    <table border="2px">
        
        {% for k, v in info.items %}
            <tr>
            <th>{{ k }}</th>
            <td>{{ v }}</td>
            </tr>
        {% endfor %}

    </table>

    </div>

{% endblock %}

templates/home.html
{% load static %}
<html lang="">
<head>
    <title>Practice</title>
    <link rel="stylesheet" href="{% static 'base/css_files/home.css'%}" type="text/css">
</head>
<body>
    <div class="home-container">
        <a href="{% url 'log_in' %}"><button>Log In</button></a>
        <a href="{% url 'create-account'%}"><button>Create-Account</button></a>
    </div>
</body>
</html>

templates/log_in.html
{% include 'nave_bar.html' %}
{% load static %}
{% block content %}
    <!--suppress ALL -->
    <div id="list-container">

    <div>
        <ul>
    <link rel="stylesheet" href="{% static 'base/css_files/log_in.css' %}" type="text/css">
    {% for i in name %}
        {% for b in i.information_set.all %}
        <a href="{% url 'account' i.id%}"><li>{{ b.name }}</li></a>

        {% endfor %}
    {% endfor %}
    </ul>
    </div>

    </div>
{% endblock %}

templates/nave_bar.html
{% load static %}

<!--suppress ALL -->
<html>
<header>
    <link rel="stylesheet" href="{% static 'base/css_files/nav_bar.css'%}">
</header>
<body>
{% block content %}
    <div id="nav-bar">
    <table border="0px">
        <tr>
            <th><a href="{% url 'home'%}">Home</a></th>
            <th><a href="{% url 'log_in' %}">Log In</a></th>
            <th><a href="{% url 'create-account'%}">Create-account</a> </th>
            <th ><a href="{%url 'status'%}">Status</a></th>
        </tr>
    </table>
    </div>
{% endblock %}
</body>
</html>

templates/payment.html
{% include 'nave_bar.html' %}
{% load static %}
<!--suppress ALL -->
<link rel="stylesheet" href="{% static 'base/css_files/payment.css'%}">
{% block content%}
    <form method="POST" action="">
    {% csrf_token %}
    {% for i in info.information_set.all%}
    <div class="information">
    <h1 id="cautions"> {{Payment}}</h1>
        <h1 id="balance">Balance: {{ i.balance }}</h1>
        <table border="2px">
            <tr>
                <th>Payment:</th>
                <td><label for="payment"></label><input id="payment" type="number" name="payment" placeholder="Amount"></td>
            </tr>
            <tr>
                <th>Name:</th>
                <td>{{ i.name }}</td>
            </tr>
            <tr>
                <th>Date:</th>
                <th>{{ date}}</th>
            </tr>
            <tr>
                <th>Dept:</th>
                <td>{{ i.dept }}</td>
            </tr>
            <tr>
                <th>Interest:</th>
                <td>{{ i.interest }}</td>
            </tr>

        </table>
    </div>
        <input type="submit" name="paid" value="saved" id="paid">
    {% endfor %}
    </form>
{% endblock %}

templates/status.html
{% load static%}
{% include 'nave_bar.html'%}
{% block content%}
<link rel="stylesheet" href="{%static 'base/css_files/status.css'%}" type="text/css">
<div class="list-container">
    <table border="1px">
        <tr align="center" id="honey">
            <th>Name</th>
            <th>Date</th>
            <th>Dept</th>
            <th>Interest</th>
            <th>Status</th>
            
        </tr>

   {%for i in info%}
        {%for v in i.information_set.all%}
             <tr>
                 <td>{{v.name}}</td>
                 <td>{{v.date.date}}</td>
                 <td>{{v.balance}}</td>
                 <td>{{v.interest}}</td>
                 {%if v.balance < 1%}
                 <td>PAID</td>
                 {%else%}
                 <td>UNPAID</td>
                 {%endif%}
                 
             </tr>
        {%endfor%}
   {%endfor%}
</table>
</div>
{%endblock%}

templates/user_account.html
{% include 'nave_bar.html' %}
{% block content %}
    <form method="POST" action="">
    {{ form.as_p }}
    </form>
{% endblock %}